package com.springboot.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "blockchain")
public class Transaction implements Serializable {

	private static final long serialVersionUID = 1L;

	private String actionId;	
	private String actionOwner;	
	private String actionDate;	
	private String actionDone;
	
	/*
	 * @Override public int hashCode() { final int prime = 31; int result = 1;
	 * result = prime * result + ((actionDate == null) ? 0 : actionDate.hashCode());
	 * result = prime * result + ((actionDone == null) ? 0 : actionDone.hashCode());
	 * result = prime * result + ((actionId == null) ? 0 : actionId.hashCode());
	 * result = prime * result + ((actionOwner == null) ? 0 :
	 * actionOwner.hashCode()); return result; }
	 * 
	 * @Override public boolean equals(Object obj) { if (this == obj) return true;
	 * if (obj == null) return false; if (getClass() != obj.getClass()) return
	 * false; Transaction other = (Transaction) obj; if (actionDate == null) { if
	 * (other.actionDate != null) return false; } else if
	 * (!actionDate.equals(other.actionDate)) return false; if (actionDone == null)
	 * { if (other.actionDone != null) return false; } else if
	 * (!actionDone.equals(other.actionDone)) return false; if (actionId == null) {
	 * if (other.actionId != null) return false; } else if
	 * (!actionId.equals(other.actionId)) return false; if (actionOwner == null) {
	 * if (other.actionOwner != null) return false; } else if
	 * (!actionOwner.equals(other.actionOwner)) return false; return true; } public
	 * Transaction(String actionId, String actionOwner, String actionDate, String
	 * actionDone) { super(); this.actionId = actionId; this.actionOwner =
	 * actionOwner; this.actionDate = actionDate; this.actionDone = actionDone; }
	 */
	@DynamoDBHashKey(attributeName = "actionId")
	@DynamoDBAutoGeneratedKey
	public String getActionId() {
		return actionId;
	}
	public void setActionId(String actionId) {
		this.actionId = actionId;
	}
	
	@DynamoDBAttribute
	public String getActionOwner() {
		return actionOwner;
	}
	public void setActionOwner(String actionOwner) {
		this.actionOwner = actionOwner;
	}
	@DynamoDBAttribute
	public String getActionDate() {
		return actionDate;
	}
	public void setActionDate(String actionDate) {
		this.actionDate = actionDate;
	}
	@DynamoDBAttribute
	public String getActionDone() {
		return actionDone;
	}
	public void setActionDone(String actionDone) {
		this.actionDone = actionDone;
	}	          
	
	
	

	
	




	
}
