package com.springboot.model;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "contract")
public class Contract implements Serializable {

	private static final long serialVersionUID = 1L;
	
	
	private String dealId;
	private String dealName;
	private String vendor;
	private String agency;
	private String dealStatus;
	private String dealType;
	private String dealFromDate;
	private String dealToDate;
	private String createdDate;
	private String dealCurrency;
	//private String program;
	
	
	@DynamoDBHashKey(attributeName = "dealId")
	@DynamoDBAutoGeneratedKey	
	public String getDealId() {
		return dealId;
	}
	public void setDealId(String dealId) {
		this.dealId = dealId;
	}
	
	/*
	 * @DynamoDBAttribute public String getProgram() { return program; } public void
	 * setProgram(String program) { this.program = " "; }
	 */
	
	@DynamoDBAttribute	
	public String getDealName() {
		return dealName;
	}
	public void setDealName(String dealName) {
		this.dealName = dealName;
	}
	@DynamoDBAttribute
	public String getVendor() {
		return vendor;
	}
	public void setVendor(String vendor) {
		this.vendor = vendor;
	}
	@DynamoDBAttribute
	public String getAgency() {
		return agency;
	}
	public void setAgency(String agency) {
		this.agency = agency;
	}
	@DynamoDBAttribute
	public String getDealStatus() {
		return dealStatus;
	}
	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}
	@DynamoDBAttribute
	public String getDealType() {
		return dealType;
	}
	public void setDealType(String dealType) {
		this.dealType = dealType;
	}
	@DynamoDBAttribute
	public String getDealFromDate() {
		return dealFromDate;
	}
	public void setDealFromDate(String dealFromDate) {
		this.dealFromDate = dealFromDate;
	}
	@DynamoDBAttribute
	public String getDealToDate() {
		return dealToDate;
	}
	public void setDealToDate(String dealToDate) {
		this.dealToDate = dealToDate;
	}
	@DynamoDBAttribute
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	@DynamoDBAttribute
	public String getDealCurrency() {
		return dealCurrency;
	}
	public void setDealCurrency(String dealCurrency) {
		this.dealCurrency = dealCurrency;
	}
	
	/*
	 * @DynamoDBAttribute public List getProgram() { return program; } public void
	 * setProgram(List program) { this.program = program; }
	 */
	
	
	
	
	
	
		
	
	

	
	
	
}
