package com.springboot.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "participants")
public class Participants implements Serializable {

	private static final long serialVersionUID = 1L;

	private String participant;	
	private String Id;	
	private String username;
	
			
	
	@DynamoDBHashKey(attributeName = "Id")	
	public String getId() {
		return Id;
	}
	public void setId(String id) {
		Id = id;
	}
	
	
	@DynamoDBAttribute
	public String getParticipant() {
		return participant;
	}
	public void setParticipant(String participant) {
		this.participant = participant;
	}
	
	
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	               
	
	
	

	
	




	
}
