package com.springboot.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "program")
public class Program implements Serializable {

	private static final long serialVersionUID = 1L;
	
	

	private String programId;
	private String programName;
	private String genre;
	private String programVideo;
	private String owner;
	
	@DynamoDBHashKey(attributeName = "programId")
	@DynamoDBAutoGeneratedKey
	public String getProgramId() {
		return programId;
	}
	public void setProgramId(String programId) {
		this.programId = programId;
	}
	
	@DynamoDBAttribute
	public String getProgramName() {
		return programName;
	}
	public void setProgramName(String programName) {
		this.programName = programName;
	}
	@DynamoDBAttribute
	public String getGenre() {
		return genre;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	@DynamoDBAttribute
	public String getProgramVideo() {
		return programVideo;
	}
	public void setProgramVideo(String programVideo) {
		this.programVideo = programVideo;
	}
	@DynamoDBAttribute
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}	
	

	
}
